### ISSUE TITLE
请问这套系统具体的开发环境是什么呢？

### ISSUE THREAD

**Issue by HowquaX** [cckevincyh/OnLineTest#1]
我用MyEclipse打开提示错误。

**Comment by cckevincyh** [comment]
能详细说下报错原因吗？

**Comment by cckevincyh** [comment]
能详细说下报什么错吗？MyEclipse最好是重新创建新一个项目，然后在直接吧src和WebRoot复制到项目中。

**Comment by HowquaX** [comment]
在OnLineTest\WebRoot\WEB-INF\lib\目录下加入jsp-api.jar和servlet-api.jar后，加入到build-path后错误解决了httpservletrequest。但现在不知道需要如何部署项目进行调试。目前在学习这一块的知识，我导出成war包后，部署到Tomcat的webapps下，通过localhost:8080访问OnLineTest提示404。

**Comment by cckevincyh** [comment]
不需要另外添加jar包，你只需要把lib目录的jar包导入，还有就是你需要创建一下数据库，数据库sql语句我已经给出了，然后你在config/hibernate/hibernate.cfg.xml中还需要对应改一下你的数据库密码。webRoot下的jquery.js文件可能会报错，你MyEclipse直接忽略就好了,这只是误报。

**Comment by cckevincyh** [comment]
如果还有问题的话，你可以QQ(835287880)和我取得联系，方便截图说明。

**Comment by mqly** [comment]
404 ,lib下面的struts2 / struts-plugin.xml报错，Package with name spring-default defined in the included configuration file

**Comment by cckevincyh** [comment]
@mqly 跟那个文件没啥关系。建议MyEclipse最好是重新创建新一个项目，然后在直接把src和WebRoot复制到项目中，然后记得把lib下的包都导入。

**Comment by zzyy17** [comment]
运行404
