### ISSUE TITLE
配置环境

### ISSUE THREAD

**Issue by jojoci** [cckevincyh/OnLineTest#5]
能问一下您的配置环境具体是什么吗，我配置一直不成功
我用的是eclipse+jdk1.8+tomcat7

**Comment by cckevincyh** [comment]
@jojoci 我之前的也是tomcat7，配置不成功可以去看看其他issues。https://github.com/cckevincyh/OnLineTest/issues/4

**Comment by cckevincyh** [comment]
@jojoci 或者你可以看看这个配置https://github.com/cckevincyh/LibrarySystem/issues/1

**Comment by jojoci** [comment]
@cckevincyh 
![Uploading image.png…]()
一直会报错
我按你之前告诉别人的那个方法试了也不行

**Comment by jojoci** [comment]
![image](https://user-images.githubusercontent.com/39588448/43500022-09379a1a-9581-11e8-9170-f589c7217596.png)

**Comment by jojoci** [comment]
按照cckevincyh/LibrarySystem#1这个配置跑起来也是404

**Comment by cckevincyh** [comment]
@jojoci 看错误应该是包没导进去。你可以截图给我看看。你目录下面包的结构吗？

**Comment by jojoci** [comment]
@cckevincyh 
![image](https://user-images.githubusercontent.com/39588448/43502449-891fbdb4-958d-11e8-841a-ac47a53d6dc7.png)

**Comment by cckevincyh** [comment]
@jojoci 你试试把所有的jar包提出来放一个lib文件夹下。别分开放。然后再重新导入试试看。

**Comment by jojoci** [comment]
我解决了，因为之前一直没有和数据库连接，才会出问题，感谢，给你笔芯芯♥

**Comment by jojoci** [comment]
@cckevincyh 
我想再问一下，我连接数据库成功了，数据库里面也加入了数据，但是登陆的时候一直显示密码错误

而且只有login页面可以显示，admin.jsp那些就会报错

**Comment by cckevincyh** [comment]
@jojoci 你已经可以跑起来了吗？数据库的密码好像有加密的。不好意思项目太久了。报错的提示是什么？

**Comment by jojoci** [comment]
@cckevincyh 是的已经可以跑起来了，我将您里面的数据库文件导入MYSQL中建库，然后自己添加的数据，因为您给的数据库文件是没有插入数据的
然后登录的时候，显示密码错误
我直接输入其他jsp页面，就会报404错误
![image](https://user-images.githubusercontent.com/39588448/43516958-b33baf1e-95b9-11e8-9bbd-86021298d0c2.png)
eclipse中错误显示为
![image](https://user-images.githubusercontent.com/39588448/43516998-d853e122-95b9-11e8-8940-cbf37b9bb174.png)

**Comment by cckevincyh** [comment]
@jojoci 之前没跑起来是什么原因呢？看错误可能是jstl没导入。看看https://blog.csdn.net/lki_suidongdong/article/details/7913908

**Comment by cckevincyh** [comment]
@jojoci 测试的admin数据你可以去OnLineTest/OnLineTest/test/com/cc/onlinetest/test/TestAdmin.java中运行添加admin的方法。

**Comment by jojoci** [comment]
@cckevincyh按照您说的 jar包提出来放一个lib文件夹下，跑了一次，报错，但是错误跟之前不一样，我查了之后发现是数据库没连上，之后连接上了就能跑起来了
加了两个依赖的jar包，现在跑起来是404.jsp就是自己写的那个404页面了
登录的按照您说的那个Java文件，他不是定了一个admin的用户吗？为什么我用admin无法登录？显示用户不存在。还是说我还需要自己再加进去

**Comment by cckevincyh** [comment]
@jojoci 运行了测试方法之后，admin有添加到数据库吗？

**Comment by jojoci** [comment]
@cckevincyh 嗯嗯，现在好了！！！感恩小哥哥！

**Comment by cckevincyh** [comment]
@jojoci 没事。
